### ISSUE TITLE
Breaks standard handling of return key

### ISSUE THREAD

**Issue by cmlenz** [obogo/angular-focus-manager#4]
Just adding the focus manager module as a dependency breaks the default browser handling of the return key in `textarea`s and `contentEditable` elements.

I've prepared a Plunk to demonstrate: http://plnkr.co/edit/wkFByJTZlRUa4uxsZKDJ

**Comment by roboncode** [comment]
Thanks looking into it.

**Comment by roboncode** [comment]
Fixed in 0.2.6
